on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/b77ee3f8c74ee8a3fefa078e4fcbadbb
          gist_title: Pr치ctica 2 - Push Button MPLAB X PIC assembler PIC18F4550
          gist_description: Pr치cticas PIC Assembler
          github_file: Proyecto/PIC18F4550/Push_button.X/push_button.s
          file_encoding: ISO-8859-1
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/9e6a5486c7ade23fa0752f482f0d2c3b
          gist_title: Pr치ctica 2 - Push Button MPLAB X PIC assembler PIC18F45K50
          gist_description: Pr치cticas PIC Assembler
          github_file: Proyecto/PIC18F45K50/Push_button.X/push_button.s
          file_encoding: ISO-8859-1